/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 07 04:57:15 GMT 2021
 */

package me.prettyprint.cassandra.connection.client;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import me.prettyprint.cassandra.connection.client.HThriftClient;
import me.prettyprint.cassandra.service.CassandraHost;
import org.apache.thrift.transport.TTransport;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class HThriftClient_ESTest extends HThriftClient_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CassandraHost cassandraHost0 = new CassandraHost("", 211);
      HThriftClient hThriftClient0 = new HThriftClient(cassandraHost0);
      // EXCEPTION DIFF:
      // The original version did not exhibit this exception:
      //     java.lang.IllegalArgumentException : object is not an instance of declaring class
      hThriftClient0.maybeWrapWithTFramedTransport((TTransport) null);
      // EXCEPTION DIFF:
      // The modified version did not exhibit this exception:
      //     org.evosuite.runtime.mock.java.lang.MockIllegalStateException : getCassandra called on client that was not open. You should not have gotten here.
      // Undeclared exception!
      try { 
        hThriftClient0.getCassandra();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // getCassandra called on client that was not open. You should not have gotten here.
         //
         verifyException("me.prettyprint.cassandra.connection.client.HThriftClient", e);
         assertTrue(e.getMessage().equals("getCassandra called on client that was not open. You should not have gotten here."));   
      }
  }
}
