/*
 * This file was automatically generated by EvoSuite
 * Mon Nov 08 18:37:07 GMT 2021
 */

package org.elasticsearch.rest.action.cat;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.elasticsearch.cluster.metadata.MetaData;
import org.elasticsearch.index.Index;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RestShardsAction_ESTest extends RestShardsAction_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // EXCEPTION DIFF:
      // The original version did not exhibit this exception:
      //     java.lang.NoClassDefFoundError : Could not initialize class org.elasticsearch.cluster.metadata.MetaData
      MetaData metaData0 = MetaData.EMPTY_META_DATA;
      Index index0 = new Index("Shard not started", "context_mode");
      // EXCEPTION DIFF:
      // The modified version did not exhibit this exception:
      //     org.elasticsearch.index.IndexNotFoundException : no such index
      // Undeclared exception!
      try { 
        metaData0.getIndexSafe(index0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no such index
         //
         verifyException("org.elasticsearch.cluster.metadata.MetaData", e);
         assertTrue(e.getMessage().equals("no such index"));   
      }
  }
}
