/*
 * This file was automatically generated by EvoSuite
 * Sat Nov 06 16:19:49 GMT 2021
 */

package org.elasticsearch.river.mongodb;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedHashSet;
import org.elasticsearch.cluster.metadata.MetaData;
import org.elasticsearch.common.settings.Settings;
import org.elasticsearch.env.Environment;
import org.elasticsearch.river.RiverSettings;
import org.elasticsearch.river.mongodb.MongoDBRiverDefinition;
import org.elasticsearch.script.ScriptEngineService;
import org.elasticsearch.script.ScriptService;
import org.elasticsearch.threadpool.ThreadPool;
import org.elasticsearch.watcher.ResourceWatcherService;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MongoDBRiverDefinition_ESTest extends MongoDBRiverDefinition_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MetaData metaData0 = MetaData.EMPTY_META_DATA;
      Settings settings0 = metaData0.settings();
      Environment environment0 = new Environment();
      LinkedHashSet<ScriptEngineService> linkedHashSet0 = new LinkedHashSet<ScriptEngineService>();
      // EXCEPTION DIFF:
      // The original version did not exhibit this exception:
      //     java.lang.IllegalArgumentException : The constructor public org.elasticsearch.threadpool.ThreadPool(java.lang.String) is not a member of type class org.elasticsearch.threadpool.ThreadPool
      ThreadPool threadPool0 = new ThreadPool("k#!Wn%");
      ResourceWatcherService resourceWatcherService0 = new ResourceWatcherService(settings0, threadPool0);
      ScriptService scriptService0 = new ScriptService(settings0, environment0, linkedHashSet0, resourceWatcherService0);
      // EXCEPTION DIFF:
      // The modified version did not exhibit this exception:
      //     org.elasticsearch.ElasticsearchNullPointerException : No settings specified
      // Undeclared exception!
      try { 
        MongoDBRiverDefinition.parseSettings("Field [", "Field [", (RiverSettings) null, scriptService0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // No settings specified
         //
         verifyException("org.elasticsearch.common.Preconditions", e);
         assertTrue(e.getMessage().equals("No settings specified"));   
      }
  }
}
