/*
 * This file was automatically generated by EvoSuite
 * Sun Nov 07 04:33:50 GMT 2021
 */

package com.zaxxer.hikari;

import org.junit.Test;
import static org.junit.Assert.*;
import com.zaxxer.hikari.HikariDataSource;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class HikariPool_ESTest extends HikariPool_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      HikariDataSource hikariDataSource0 = new HikariDataSource();
      // EXCEPTION DIFF:
      // The original version did not exhibit this exception:
      //     org.evosuite.testcase.execution.CodeUnderTestException : java.lang.IllegalArgumentException: Cannot assignable: true of class class java.lang.Boolean to field public boolean com.zaxxer.hikari.HikariConfig.isIsolateInternalQueries of variable VariableReference: Statement 0, type com.zaxxer.hikari.HikariDataSource
      hikariDataSource0.isIsolateInternalQueries = true;
  }
}
