/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Nov 08 12:18:55 GMT 2021
 */

package rx.concurrency;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class TestScheduler_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "rx.concurrency.TestScheduler"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    /*No java.lang.System property to set*/
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(TestScheduler_ESTest_scaffolding.class.getClassLoader() ,
      "rx.operators.OperationSynchronize$Synchronize",
      "rx.operators.OperationInterval$Interval",
      "rx.operators.OperationFilter$Filter",
      "rx.operators.OperationThrottle$ThrottledOnNext",
      "rx.operators.OperationConcat$ConcatSubscription",
      "rx.util.functions.Action0",
      "rx.operators.OperationSubscribeOn$SubscribeOn",
      "rx.concurrency.ExecutorScheduler",
      "rx.operators.OperationMaterialize$MaterializeObservable",
      "rx.operators.OperationToObservableList$ToObservableList",
      "rx.operators.OperationTakeLast$TakeLast",
      "rx.concurrency.TestScheduler$1",
      "rx.operators.OperationFinally$Finally",
      "rx.operators.OperationThrottle$ThrottledOnError",
      "rx.operators.OperationSkip$Skip",
      "rx.operators.OperationTake$Take",
      "rx.operators.OperationThrottle$Throttle",
      "rx.operators.OperationObserveOn$ObserveOn",
      "rx.concurrency.ImmediateScheduler",
      "rx.concurrency.SleepingAction",
      "rx.operators.OperationGroupBy$GroupBy",
      "rx.operators.OperationMerge$MergeObservable$MergeSubscription",
      "rx.operators.OperationToObservableIterable$ToObservableIterable",
      "rx.Scheduler$11",
      "rx.util.SynchronizedObserver$UnitTest$TestMultiThreadedObservable",
      "rx.Scheduler",
      "rx.concurrency.TestScheduler",
      "rx.operators.OperationOnErrorResumeNextViaObservable$OnErrorResumeNextViaObservable",
      "rx.operators.OperationTakeWhile$TakeWhile",
      "rx.concurrency.TestScheduler$CompareActionsByTime",
      "rx.operators.OperationScan$Accumulator",
      "rx.operators.OperationOnErrorResumeNextViaFunction$OnErrorResumeNextViaFunction",
      "rx.operators.OperationToObservableSortedList$ToObservableSortedList$DefaultComparableFunction",
      "rx.Subscription",
      "rx.subscriptions.BooleanSubscription",
      "rx.util.AtomicObservableSubscription",
      "rx.operators.OperationThrottle$ThrottledOnComplete",
      "rx.operators.OperationMergeDelayError$MergeDelayErrorObservable",
      "rx.operators.OperationSubscribeOn$ScheduledSubscription",
      "rx.Scheduler$1",
      "rx.Scheduler$2",
      "rx.operators.OperatorTester$UnitTest$ForwardingScheduler",
      "rx.operators.OperationZip$Aggregator",
      "rx.concurrency.ImmediateScheduler$1",
      "rx.operators.OperationSample$Sample",
      "rx.operators.OperationToObservableFuture$ToObservableFuture",
      "rx.subscriptions.Subscriptions",
      "rx.operators.OperationAll$AllObservable",
      "rx.operators.OperationTakeUntil$SourceObservable",
      "rx.util.functions.Functions$Identity",
      "rx.subjects.ReplaySubject$SubscriptionFunc",
      "rx.operators.OperatorTester",
      "rx.operators.OperationOnErrorReturn$OnErrorReturn",
      "rx.util.functions.Func1",
      "rx.operators.OperationMerge$MergeObservable",
      "rx.util.functions.Func2",
      "rx.util.functions.Func0",
      "rx.operators.OperationCombineLatest$Aggregator",
      "rx.concurrency.DiscardableAction",
      "rx.subjects.ReplaySubject$DelegateSubscriptionFunc",
      "rx.operators.OperationTakeUntil$OtherObservable",
      "rx.operators.OperationToObservableSortedList$ToObservableSortedList",
      "rx.operators.OperationDematerialize$DematerializeObservable",
      "rx.concurrency.TestScheduler$TimedAction",
      "rx.subscriptions.CompositeSubscription",
      "rx.subscriptions.Subscriptions$1",
      "rx.util.functions.Function",
      "rx.operators.OperationMap$MapObservable",
      "rx.operators.OperationMergeDelayError$MergeDelayErrorObservable$MergeSubscription",
      "rx.subscriptions.Subscriptions$4",
      "rx.concurrency.NewThreadScheduler",
      "rx.concurrency.CurrentThreadScheduler$1",
      "rx.util.functions.Functions$AlwaysTrue",
      "rx.util.SynchronizedObserver$UnitTest$TestSingleThreadedObservable",
      "rx.concurrency.CurrentThreadScheduler$TimedAction",
      "rx.subjects.ReplaySubject$RepeatSubjectSubscription",
      "rx.operators.OperatorTester$UnitTest",
      "rx.concurrency.CurrentThreadScheduler"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(TestScheduler_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "rx.Scheduler",
      "rx.concurrency.TestScheduler",
      "rx.concurrency.TestScheduler$TimedAction",
      "rx.concurrency.TestScheduler$1",
      "rx.concurrency.TestScheduler$CompareActionsByTime",
      "rx.concurrency.SleepingAction",
      "rx.concurrency.ImmediateScheduler",
      "rx.Scheduler$11",
      "rx.Scheduler$1",
      "rx.Scheduler$2",
      "rx.subscriptions.Subscriptions$4",
      "rx.subscriptions.Subscriptions",
      "rx.subscriptions.Subscriptions$1",
      "rx.subscriptions.BooleanSubscription"
    );
  }
}
