/*
 * This file was automatically generated by EvoSuite
 * Sat Nov 06 14:20:16 GMT 2021
 */

package org.elasticsearch.action.delete;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.elasticsearch.action.WriteConsistencyLevel;
import org.elasticsearch.action.delete.DeleteRequest;
import org.elasticsearch.action.delete.TransportDeleteAction;
import org.elasticsearch.action.support.WriteRequest;
import org.elasticsearch.cluster.metadata.MetaData;
import org.elasticsearch.index.VersionType;
import org.elasticsearch.index.shard.IndexShard;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TransportDeleteAction_ESTest extends TransportDeleteAction_ESTest_scaffolding {

  @Test(timeout = 11000)
  public void test00()  throws Throwable  {
      MetaData metaData0 = MetaData.PROTO;
      assertNotNull(metaData0);
      assertEquals(0L, metaData0.version());
      assertEquals(0, metaData0.getNumberOfShards());
      assertEquals(0, metaData0.getTotalNumberOfShards());
      assertEquals("_na_", metaData0.clusterUUID());
      
      DeleteRequest deleteRequest0 = new DeleteRequest();
      assertNotNull(deleteRequest0);
      assertNull(deleteRequest0.index());
      assertFalse(deleteRequest0.getShouldPersistResult());
      assertNull(deleteRequest0.parent());
      assertNull(deleteRequest0.routing());
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest0.consistencyLevel());
      assertEquals((-3L), deleteRequest0.version());
      assertNull(deleteRequest0.type());
      assertNull(deleteRequest0.id());
      assertEquals(0L, deleteRequest0.primaryTerm());
      assertEquals(VersionType.INTERNAL, deleteRequest0.versionType());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest0.getRefreshPolicy());
      
      TransportDeleteAction.resolveAndValidateRouting(metaData0, metaData0.CONTEXT_MODE_GATEWAY, deleteRequest0);
      assertEquals(0L, metaData0.version());
      assertEquals(0, metaData0.getNumberOfShards());
      assertEquals(0, metaData0.getTotalNumberOfShards());
      assertEquals("_na_", metaData0.clusterUUID());
      assertNull(deleteRequest0.index());
      assertFalse(deleteRequest0.getShouldPersistResult());
      assertNull(deleteRequest0.parent());
      assertNull(deleteRequest0.routing());
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest0.consistencyLevel());
      assertEquals((-3L), deleteRequest0.version());
      assertNull(deleteRequest0.type());
      assertNull(deleteRequest0.id());
      assertEquals(0L, deleteRequest0.primaryTerm());
      assertEquals(VersionType.INTERNAL, deleteRequest0.versionType());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest0.getRefreshPolicy());
      
      TransportDeleteAction.resolveAndValidateRouting(metaData0, metaData0.GLOBAL_STATE_FILE_PREFIX, deleteRequest0);
      assertEquals(0L, metaData0.version());
      assertEquals(0, metaData0.getNumberOfShards());
      assertEquals(0, metaData0.getTotalNumberOfShards());
      assertEquals("_na_", metaData0.clusterUUID());
      assertNull(deleteRequest0.index());
      assertFalse(deleteRequest0.getShouldPersistResult());
      assertNull(deleteRequest0.parent());
      assertNull(deleteRequest0.routing());
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest0.consistencyLevel());
      assertEquals((-3L), deleteRequest0.version());
      assertNull(deleteRequest0.type());
      assertNull(deleteRequest0.id());
      assertEquals(0L, deleteRequest0.primaryTerm());
      assertEquals(VersionType.INTERNAL, deleteRequest0.versionType());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest0.getRefreshPolicy());
  }

  @Test(timeout = 11000)
  public void test01()  throws Throwable  {
      IndexShard indexShard0 = null;
      DeleteRequest deleteRequest0 = null;
      // Undeclared exception!
      try { 
        TransportDeleteAction.executeDeleteRequestOnReplica(deleteRequest0, indexShard0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.elasticsearch.action.delete.TransportDeleteAction", e);
      }
  }

  @Test(timeout = 11000)
  public void test02()  throws Throwable  {
      DeleteRequest deleteRequest0 = new DeleteRequest();
      assertNotNull(deleteRequest0);
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest0.getRefreshPolicy());
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest0.consistencyLevel());
      assertNull(deleteRequest0.routing());
      assertFalse(deleteRequest0.getShouldPersistResult());
      assertEquals(0L, deleteRequest0.primaryTerm());
      assertEquals((-3L), deleteRequest0.version());
      assertNull(deleteRequest0.type());
      assertNull(deleteRequest0.id());
      assertEquals(VersionType.INTERNAL, deleteRequest0.versionType());
      assertNull(deleteRequest0.parent());
      assertNull(deleteRequest0.index());
      
      IndexShard indexShard0 = null;
      // Undeclared exception!
      try { 
        TransportDeleteAction.executeDeleteRequestOnPrimary(deleteRequest0, indexShard0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.elasticsearch.action.delete.TransportDeleteAction", e);
      }
  }

  @Test(timeout = 11000)
  public void test03()  throws Throwable  {
      MetaData metaData0 = MetaData.PROTO;
      assertNotNull(metaData0);
      assertEquals(0, metaData0.getTotalNumberOfShards());
      assertEquals(0L, metaData0.version());
      assertEquals(0, metaData0.getNumberOfShards());
      assertEquals("_na_", metaData0.clusterUUID());
      
      DeleteRequest deleteRequest0 = new DeleteRequest();
      assertNotNull(deleteRequest0);
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest0.consistencyLevel());
      assertNull(deleteRequest0.routing());
      assertNull(deleteRequest0.parent());
      assertNull(deleteRequest0.index());
      assertFalse(deleteRequest0.getShouldPersistResult());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest0.getRefreshPolicy());
      assertNull(deleteRequest0.id());
      assertEquals(VersionType.INTERNAL, deleteRequest0.versionType());
      assertEquals(0L, deleteRequest0.primaryTerm());
      assertEquals((-3L), deleteRequest0.version());
      assertNull(deleteRequest0.type());
      
      DeleteRequest deleteRequest1 = deleteRequest0.routing(metaData0.CONTEXT_MODE_SNAPSHOT);
      assertNotNull(deleteRequest1);
      assertSame(deleteRequest0, deleteRequest1);
      assertSame(deleteRequest1, deleteRequest0);
      assertEquals(0, metaData0.getTotalNumberOfShards());
      assertEquals(0L, metaData0.version());
      assertEquals(0, metaData0.getNumberOfShards());
      assertEquals("_na_", metaData0.clusterUUID());
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest0.consistencyLevel());
      assertNull(deleteRequest0.parent());
      assertNull(deleteRequest0.index());
      assertFalse(deleteRequest0.getShouldPersistResult());
      assertEquals("SNAPSHOT", deleteRequest0.routing());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest0.getRefreshPolicy());
      assertNull(deleteRequest0.id());
      assertEquals(VersionType.INTERNAL, deleteRequest0.versionType());
      assertEquals(0L, deleteRequest0.primaryTerm());
      assertEquals((-3L), deleteRequest0.version());
      assertNull(deleteRequest0.type());
      assertEquals(0L, deleteRequest1.primaryTerm());
      assertEquals((-3L), deleteRequest1.version());
      assertNull(deleteRequest1.type());
      assertNull(deleteRequest1.index());
      assertFalse(deleteRequest1.getShouldPersistResult());
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest1.consistencyLevel());
      assertNull(deleteRequest1.parent());
      assertEquals(VersionType.INTERNAL, deleteRequest1.versionType());
      assertEquals("SNAPSHOT", deleteRequest1.routing());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest1.getRefreshPolicy());
      assertNull(deleteRequest1.id());
      
      TransportDeleteAction.resolveAndValidateRouting(metaData0, metaData0.ALL, deleteRequest1);
      assertSame(deleteRequest0, deleteRequest1);
      assertSame(deleteRequest1, deleteRequest0);
      assertEquals(0, metaData0.getTotalNumberOfShards());
      assertEquals(0L, metaData0.version());
      assertEquals(0, metaData0.getNumberOfShards());
      assertEquals("_na_", metaData0.clusterUUID());
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest0.consistencyLevel());
      assertNull(deleteRequest0.parent());
      assertNull(deleteRequest0.index());
      assertFalse(deleteRequest0.getShouldPersistResult());
      assertEquals("SNAPSHOT", deleteRequest0.routing());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest0.getRefreshPolicy());
      assertNull(deleteRequest0.id());
      assertEquals(VersionType.INTERNAL, deleteRequest0.versionType());
      assertEquals(0L, deleteRequest0.primaryTerm());
      assertEquals((-3L), deleteRequest0.version());
      assertNull(deleteRequest0.type());
      assertEquals(0L, deleteRequest1.primaryTerm());
      assertEquals((-3L), deleteRequest1.version());
      assertNull(deleteRequest1.type());
      assertNull(deleteRequest1.index());
      assertFalse(deleteRequest1.getShouldPersistResult());
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest1.consistencyLevel());
      assertNull(deleteRequest1.parent());
      assertEquals(VersionType.INTERNAL, deleteRequest1.versionType());
      assertEquals("SNAPSHOT", deleteRequest1.routing());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest1.getRefreshPolicy());
      assertNull(deleteRequest1.id());
  }

  @Test(timeout = 11000)
  public void test04()  throws Throwable  {
      DeleteRequest deleteRequest0 = null;
      IndexShard indexShard0 = null;
      // Undeclared exception!
      try { 
        TransportDeleteAction.executeDeleteRequestOnReplica(deleteRequest0, indexShard0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.elasticsearch.action.delete.TransportDeleteAction", e);
      }
  }

  @Test(timeout = 11000)
  public void test05()  throws Throwable  {
      DeleteRequest deleteRequest0 = new DeleteRequest();
      assertNotNull(deleteRequest0);
      assertNull(deleteRequest0.id());
      assertEquals(0L, deleteRequest0.primaryTerm());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest0.getRefreshPolicy());
      assertEquals(VersionType.INTERNAL, deleteRequest0.versionType());
      assertNull(deleteRequest0.parent());
      assertNull(deleteRequest0.index());
      assertFalse(deleteRequest0.getShouldPersistResult());
      assertNull(deleteRequest0.type());
      assertEquals((-3L), deleteRequest0.version());
      assertNull(deleteRequest0.routing());
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest0.consistencyLevel());
      
      IndexShard indexShard0 = null;
      // Undeclared exception!
      try { 
        TransportDeleteAction.executeDeleteRequestOnReplica(deleteRequest0, indexShard0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.elasticsearch.action.delete.TransportDeleteAction", e);
      }
  }

  @Test(timeout = 11000)
  public void test06()  throws Throwable  {
      MetaData metaData0 = MetaData.PROTO;
      assertNotNull(metaData0);
      assertEquals(0, metaData0.getTotalNumberOfShards());
      assertEquals(0, metaData0.getNumberOfShards());
      assertEquals("_na_", metaData0.clusterUUID());
      assertEquals(0L, metaData0.version());
      
      DeleteRequest deleteRequest0 = null;
      // Undeclared exception!
      try { 
        TransportDeleteAction.resolveAndValidateRouting(metaData0, metaData0.CONTEXT_MODE_SNAPSHOT, deleteRequest0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.elasticsearch.action.delete.TransportDeleteAction", e);
      }
  }

  @Test(timeout = 11000)
  public void test07()  throws Throwable  {
      DeleteRequest deleteRequest0 = null;
      IndexShard indexShard0 = null;
      // Undeclared exception!
      try { 
        TransportDeleteAction.executeDeleteRequestOnPrimary(deleteRequest0, indexShard0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.elasticsearch.action.delete.TransportDeleteAction", e);
      }
  }

  @Test(timeout = 11000)
  public void test08()  throws Throwable  {
      MetaData metaData0 = MetaData.EMPTY_META_DATA;
      assertNotNull(metaData0);
      assertEquals("_na_", metaData0.clusterUUID());
      assertEquals(0, metaData0.getNumberOfShards());
      assertEquals(0, metaData0.getTotalNumberOfShards());
      assertEquals(0L, metaData0.version());
      
      String string0 = "indices:data/write/delete";
      DeleteRequest deleteRequest0 = new DeleteRequest(metaData0.ALL, string0, metaData0.CONTEXT_MODE_GATEWAY);
      assertNotNull(deleteRequest0);
      assertEquals("_na_", metaData0.clusterUUID());
      assertEquals(0, metaData0.getNumberOfShards());
      assertEquals(0, metaData0.getTotalNumberOfShards());
      assertEquals(0L, metaData0.version());
      assertNull(deleteRequest0.parent());
      assertFalse(deleteRequest0.getShouldPersistResult());
      assertNull(deleteRequest0.routing());
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest0.consistencyLevel());
      assertEquals("_all", deleteRequest0.index());
      assertEquals((-3L), deleteRequest0.version());
      assertEquals("indices:data/write/delete", deleteRequest0.type());
      assertEquals(0L, deleteRequest0.primaryTerm());
      assertEquals(VersionType.INTERNAL, deleteRequest0.versionType());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest0.getRefreshPolicy());
      assertEquals("GATEWAY", deleteRequest0.id());
      
      TransportDeleteAction.resolveAndValidateRouting(metaData0, metaData0.GLOBAL_STATE_FILE_PREFIX, deleteRequest0);
      assertEquals("_na_", metaData0.clusterUUID());
      assertEquals(0, metaData0.getNumberOfShards());
      assertEquals(0, metaData0.getTotalNumberOfShards());
      assertEquals(0L, metaData0.version());
      assertNull(deleteRequest0.parent());
      assertFalse(deleteRequest0.getShouldPersistResult());
      assertNull(deleteRequest0.routing());
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest0.consistencyLevel());
      assertEquals("_all", deleteRequest0.index());
      assertEquals((-3L), deleteRequest0.version());
      assertEquals("indices:data/write/delete", deleteRequest0.type());
      assertEquals(0L, deleteRequest0.primaryTerm());
      assertEquals(VersionType.INTERNAL, deleteRequest0.versionType());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest0.getRefreshPolicy());
      assertEquals("GATEWAY", deleteRequest0.id());
  }

  @Test(timeout = 11000)
  public void test09()  throws Throwable  {
      MetaData metaData0 = null;
      String string0 = "LC";
      String string1 = "X>G";
      DeleteRequest deleteRequest0 = new DeleteRequest(string1);
      assertNotNull(deleteRequest0);
      assertFalse(string1.equals((Object)string0));
      assertEquals(0L, deleteRequest0.primaryTerm());
      assertEquals(VersionType.INTERNAL, deleteRequest0.versionType());
      assertNull(deleteRequest0.id());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest0.getRefreshPolicy());
      assertNull(deleteRequest0.parent());
      assertFalse(deleteRequest0.getShouldPersistResult());
      assertNull(deleteRequest0.routing());
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest0.consistencyLevel());
      assertEquals("X>G", deleteRequest0.index());
      assertEquals((-3L), deleteRequest0.version());
      assertNull(deleteRequest0.type());
      
      VersionType versionType0 = VersionType.EXTERNAL;
      DeleteRequest deleteRequest1 = deleteRequest0.versionType(versionType0);
      assertNotNull(deleteRequest1);
      assertFalse(string1.equals((Object)string0));
      assertNotSame(string1, string0);
      assertSame(deleteRequest0, deleteRequest1);
      assertSame(deleteRequest1, deleteRequest0);
      assertEquals(0L, deleteRequest0.primaryTerm());
      assertEquals(VersionType.EXTERNAL, deleteRequest0.versionType());
      assertNull(deleteRequest0.id());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest0.getRefreshPolicy());
      assertNull(deleteRequest0.parent());
      assertFalse(deleteRequest0.getShouldPersistResult());
      assertNull(deleteRequest0.routing());
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest0.consistencyLevel());
      assertEquals("X>G", deleteRequest0.index());
      assertEquals((-3L), deleteRequest0.version());
      assertNull(deleteRequest0.type());
      assertNull(deleteRequest1.parent());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest1.getRefreshPolicy());
      assertEquals("X>G", deleteRequest1.index());
      assertEquals(VersionType.EXTERNAL, deleteRequest1.versionType());
      assertFalse(deleteRequest1.getShouldPersistResult());
      assertNull(deleteRequest1.routing());
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest1.consistencyLevel());
      assertEquals(0L, deleteRequest1.primaryTerm());
      assertEquals((-3L), deleteRequest1.version());
      assertNull(deleteRequest1.id());
      assertNull(deleteRequest1.type());
      
      String string2 = "";
      DeleteRequest deleteRequest2 = deleteRequest1.id(string2);
      assertNotNull(deleteRequest2);
      assertFalse(string1.equals((Object)string0));
      assertFalse(string1.equals((Object)string2));
      assertFalse(string2.equals((Object)string0));
      assertFalse(string2.equals((Object)string1));
      assertNotSame(string1, string0);
      assertNotSame(string1, string2);
      assertSame(deleteRequest0, deleteRequest1);
      assertSame(deleteRequest0, deleteRequest2);
      assertSame(deleteRequest1, deleteRequest2);
      assertSame(deleteRequest1, deleteRequest0);
      assertNotSame(string2, string0);
      assertNotSame(string2, string1);
      assertSame(deleteRequest2, deleteRequest0);
      assertSame(deleteRequest2, deleteRequest1);
      assertEquals(0L, deleteRequest0.primaryTerm());
      assertEquals(VersionType.EXTERNAL, deleteRequest0.versionType());
      assertEquals("", deleteRequest0.id());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest0.getRefreshPolicy());
      assertNull(deleteRequest0.parent());
      assertFalse(deleteRequest0.getShouldPersistResult());
      assertNull(deleteRequest0.routing());
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest0.consistencyLevel());
      assertEquals("X>G", deleteRequest0.index());
      assertEquals((-3L), deleteRequest0.version());
      assertNull(deleteRequest0.type());
      assertNull(deleteRequest1.parent());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest1.getRefreshPolicy());
      assertEquals("X>G", deleteRequest1.index());
      assertEquals(VersionType.EXTERNAL, deleteRequest1.versionType());
      assertFalse(deleteRequest1.getShouldPersistResult());
      assertNull(deleteRequest1.routing());
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest1.consistencyLevel());
      assertEquals(0L, deleteRequest1.primaryTerm());
      assertEquals((-3L), deleteRequest1.version());
      assertEquals("", deleteRequest1.id());
      assertNull(deleteRequest1.type());
      assertNull(deleteRequest2.type());
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest2.consistencyLevel());
      assertNull(deleteRequest2.routing());
      assertEquals((-3L), deleteRequest2.version());
      assertEquals(VersionType.EXTERNAL, deleteRequest2.versionType());
      assertEquals("X>G", deleteRequest2.index());
      assertFalse(deleteRequest2.getShouldPersistResult());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest2.getRefreshPolicy());
      assertEquals("", deleteRequest2.id());
      assertEquals(0L, deleteRequest2.primaryTerm());
      assertNull(deleteRequest2.parent());
      
      String string3 = ";!yc|<+-F`3&2s!+c|A";
      DeleteRequest deleteRequest3 = deleteRequest1.index(string3);
      assertNotNull(deleteRequest3);
      assertFalse(string1.equals((Object)string0));
      assertFalse(string1.equals((Object)string2));
      assertFalse(string1.equals((Object)string3));
      assertFalse(string3.equals((Object)string2));
      assertFalse(string3.equals((Object)string0));
      assertFalse(string3.equals((Object)string1));
      assertNotSame(string1, string0);
      assertNotSame(string1, string2);
      assertNotSame(string1, string3);
      assertSame(deleteRequest0, deleteRequest1);
      assertSame(deleteRequest0, deleteRequest2);
      assertSame(deleteRequest0, deleteRequest3);
      assertSame(deleteRequest1, deleteRequest2);
      assertSame(deleteRequest1, deleteRequest0);
      assertSame(deleteRequest1, deleteRequest3);
      assertNotSame(string3, string2);
      assertNotSame(string3, string0);
      assertNotSame(string3, string1);
      assertSame(deleteRequest3, deleteRequest1);
      assertSame(deleteRequest3, deleteRequest2);
      assertSame(deleteRequest3, deleteRequest0);
      assertEquals(0L, deleteRequest0.primaryTerm());
      assertEquals(VersionType.EXTERNAL, deleteRequest0.versionType());
      assertEquals(";!yc|<+-F`3&2s!+c|A", deleteRequest0.index());
      assertEquals("", deleteRequest0.id());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest0.getRefreshPolicy());
      assertNull(deleteRequest0.parent());
      assertFalse(deleteRequest0.getShouldPersistResult());
      assertNull(deleteRequest0.routing());
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest0.consistencyLevel());
      assertEquals((-3L), deleteRequest0.version());
      assertNull(deleteRequest0.type());
      assertNull(deleteRequest1.parent());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest1.getRefreshPolicy());
      assertEquals(VersionType.EXTERNAL, deleteRequest1.versionType());
      assertFalse(deleteRequest1.getShouldPersistResult());
      assertNull(deleteRequest1.routing());
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest1.consistencyLevel());
      assertEquals(0L, deleteRequest1.primaryTerm());
      assertEquals((-3L), deleteRequest1.version());
      assertEquals(";!yc|<+-F`3&2s!+c|A", deleteRequest1.index());
      assertEquals("", deleteRequest1.id());
      assertNull(deleteRequest1.type());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest3.getRefreshPolicy());
      assertNull(deleteRequest3.parent());
      assertNull(deleteRequest3.type());
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest3.consistencyLevel());
      assertEquals((-3L), deleteRequest3.version());
      assertEquals(VersionType.EXTERNAL, deleteRequest3.versionType());
      assertFalse(deleteRequest3.getShouldPersistResult());
      assertEquals(0L, deleteRequest3.primaryTerm());
      assertNull(deleteRequest3.routing());
      assertEquals("", deleteRequest3.id());
      assertEquals(";!yc|<+-F`3&2s!+c|A", deleteRequest3.index());
      
      String string4 = "V`T-WkX0bOf";
      DeleteRequest deleteRequest4 = deleteRequest2.routing(string4);
      assertNotNull(deleteRequest4);
      assertFalse(string1.equals((Object)string0));
      assertFalse(string1.equals((Object)string2));
      assertFalse(string1.equals((Object)string4));
      assertFalse(string1.equals((Object)string3));
      assertFalse(string2.equals((Object)string3));
      assertFalse(string2.equals((Object)string0));
      assertFalse(string2.equals((Object)string1));
      assertFalse(string2.equals((Object)string4));
      assertFalse(string4.equals((Object)string0));
      assertFalse(string4.equals((Object)string2));
      assertFalse(string4.equals((Object)string1));
      assertFalse(string4.equals((Object)string3));
      assertNotSame(string1, string0);
      assertNotSame(string1, string2);
      assertNotSame(string1, string4);
      assertNotSame(string1, string3);
      assertSame(deleteRequest0, deleteRequest4);
      assertSame(deleteRequest0, deleteRequest1);
      assertSame(deleteRequest0, deleteRequest2);
      assertSame(deleteRequest0, deleteRequest3);
      assertSame(deleteRequest1, deleteRequest4);
      assertSame(deleteRequest1, deleteRequest2);
      assertSame(deleteRequest1, deleteRequest0);
      assertSame(deleteRequest1, deleteRequest3);
      assertNotSame(string2, string3);
      assertNotSame(string2, string0);
      assertNotSame(string2, string1);
      assertNotSame(string2, string4);
      assertSame(deleteRequest2, deleteRequest3);
      assertSame(deleteRequest2, deleteRequest4);
      assertSame(deleteRequest2, deleteRequest0);
      assertSame(deleteRequest2, deleteRequest1);
      assertNotSame(string4, string0);
      assertNotSame(string4, string2);
      assertNotSame(string4, string1);
      assertNotSame(string4, string3);
      assertSame(deleteRequest4, deleteRequest2);
      assertSame(deleteRequest4, deleteRequest3);
      assertSame(deleteRequest4, deleteRequest1);
      assertSame(deleteRequest4, deleteRequest0);
      assertEquals(0L, deleteRequest0.primaryTerm());
      assertEquals(VersionType.EXTERNAL, deleteRequest0.versionType());
      assertEquals("V`T-WkX0bOf", deleteRequest0.routing());
      assertEquals(";!yc|<+-F`3&2s!+c|A", deleteRequest0.index());
      assertEquals("", deleteRequest0.id());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest0.getRefreshPolicy());
      assertNull(deleteRequest0.parent());
      assertFalse(deleteRequest0.getShouldPersistResult());
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest0.consistencyLevel());
      assertEquals((-3L), deleteRequest0.version());
      assertNull(deleteRequest0.type());
      assertNull(deleteRequest1.parent());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest1.getRefreshPolicy());
      assertEquals(VersionType.EXTERNAL, deleteRequest1.versionType());
      assertFalse(deleteRequest1.getShouldPersistResult());
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest1.consistencyLevel());
      assertEquals(0L, deleteRequest1.primaryTerm());
      assertEquals((-3L), deleteRequest1.version());
      assertEquals("V`T-WkX0bOf", deleteRequest1.routing());
      assertEquals(";!yc|<+-F`3&2s!+c|A", deleteRequest1.index());
      assertEquals("", deleteRequest1.id());
      assertNull(deleteRequest1.type());
      assertNull(deleteRequest2.type());
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest2.consistencyLevel());
      assertEquals((-3L), deleteRequest2.version());
      assertEquals(VersionType.EXTERNAL, deleteRequest2.versionType());
      assertFalse(deleteRequest2.getShouldPersistResult());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest2.getRefreshPolicy());
      assertEquals("", deleteRequest2.id());
      assertEquals(";!yc|<+-F`3&2s!+c|A", deleteRequest2.index());
      assertEquals(0L, deleteRequest2.primaryTerm());
      assertNull(deleteRequest2.parent());
      assertEquals("V`T-WkX0bOf", deleteRequest2.routing());
      assertEquals((-3L), deleteRequest4.version());
      assertEquals(0L, deleteRequest4.primaryTerm());
      assertEquals(VersionType.EXTERNAL, deleteRequest4.versionType());
      assertNull(deleteRequest4.type());
      assertNull(deleteRequest4.parent());
      assertFalse(deleteRequest4.getShouldPersistResult());
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest4.consistencyLevel());
      assertEquals("V`T-WkX0bOf", deleteRequest4.routing());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest4.getRefreshPolicy());
      assertEquals(";!yc|<+-F`3&2s!+c|A", deleteRequest4.index());
      assertEquals("", deleteRequest4.id());
      
      DeleteRequest deleteRequest5 = deleteRequest4.timeout(deleteRequest0.DEFAULT_TIMEOUT);
      assertNotNull(deleteRequest5);
      assertFalse(string1.equals((Object)string0));
      assertFalse(string1.equals((Object)string2));
      assertFalse(string1.equals((Object)string4));
      assertFalse(string1.equals((Object)string3));
      assertFalse(string2.equals((Object)string3));
      assertFalse(string2.equals((Object)string0));
      assertFalse(string2.equals((Object)string1));
      assertFalse(string2.equals((Object)string4));
      assertFalse(string4.equals((Object)string0));
      assertFalse(string4.equals((Object)string2));
      assertFalse(string4.equals((Object)string1));
      assertFalse(string4.equals((Object)string3));
      assertNotSame(string1, string0);
      assertNotSame(string1, string2);
      assertNotSame(string1, string4);
      assertNotSame(string1, string3);
      assertSame(deleteRequest0, deleteRequest5);
      assertSame(deleteRequest0, deleteRequest4);
      assertSame(deleteRequest0, deleteRequest1);
      assertSame(deleteRequest0, deleteRequest2);
      assertSame(deleteRequest0, deleteRequest3);
      assertSame(deleteRequest1, deleteRequest4);
      assertSame(deleteRequest1, deleteRequest2);
      assertSame(deleteRequest1, deleteRequest0);
      assertSame(deleteRequest1, deleteRequest3);
      assertSame(deleteRequest1, deleteRequest5);
      assertNotSame(string2, string3);
      assertNotSame(string2, string0);
      assertNotSame(string2, string1);
      assertNotSame(string2, string4);
      assertSame(deleteRequest2, deleteRequest3);
      assertSame(deleteRequest2, deleteRequest4);
      assertSame(deleteRequest2, deleteRequest5);
      assertSame(deleteRequest2, deleteRequest0);
      assertSame(deleteRequest2, deleteRequest1);
      assertNotSame(string4, string0);
      assertNotSame(string4, string2);
      assertNotSame(string4, string1);
      assertNotSame(string4, string3);
      assertSame(deleteRequest4, deleteRequest2);
      assertSame(deleteRequest4, deleteRequest3);
      assertSame(deleteRequest4, deleteRequest5);
      assertSame(deleteRequest4, deleteRequest1);
      assertSame(deleteRequest4, deleteRequest0);
      assertSame(deleteRequest5, deleteRequest0);
      assertSame(deleteRequest5, deleteRequest1);
      assertSame(deleteRequest5, deleteRequest3);
      assertSame(deleteRequest5, deleteRequest4);
      assertSame(deleteRequest5, deleteRequest2);
      assertEquals(0L, deleteRequest0.primaryTerm());
      assertEquals(VersionType.EXTERNAL, deleteRequest0.versionType());
      assertEquals("V`T-WkX0bOf", deleteRequest0.routing());
      assertEquals(";!yc|<+-F`3&2s!+c|A", deleteRequest0.index());
      assertEquals("", deleteRequest0.id());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest0.getRefreshPolicy());
      assertNull(deleteRequest0.parent());
      assertFalse(deleteRequest0.getShouldPersistResult());
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest0.consistencyLevel());
      assertEquals((-3L), deleteRequest0.version());
      assertNull(deleteRequest0.type());
      assertNull(deleteRequest1.parent());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest1.getRefreshPolicy());
      assertEquals(VersionType.EXTERNAL, deleteRequest1.versionType());
      assertFalse(deleteRequest1.getShouldPersistResult());
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest1.consistencyLevel());
      assertEquals(0L, deleteRequest1.primaryTerm());
      assertEquals((-3L), deleteRequest1.version());
      assertEquals("V`T-WkX0bOf", deleteRequest1.routing());
      assertEquals(";!yc|<+-F`3&2s!+c|A", deleteRequest1.index());
      assertEquals("", deleteRequest1.id());
      assertNull(deleteRequest1.type());
      assertNull(deleteRequest2.type());
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest2.consistencyLevel());
      assertEquals((-3L), deleteRequest2.version());
      assertEquals(VersionType.EXTERNAL, deleteRequest2.versionType());
      assertFalse(deleteRequest2.getShouldPersistResult());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest2.getRefreshPolicy());
      assertEquals("", deleteRequest2.id());
      assertEquals(";!yc|<+-F`3&2s!+c|A", deleteRequest2.index());
      assertEquals(0L, deleteRequest2.primaryTerm());
      assertNull(deleteRequest2.parent());
      assertEquals("V`T-WkX0bOf", deleteRequest2.routing());
      assertEquals((-3L), deleteRequest4.version());
      assertEquals(0L, deleteRequest4.primaryTerm());
      assertEquals(VersionType.EXTERNAL, deleteRequest4.versionType());
      assertNull(deleteRequest4.type());
      assertNull(deleteRequest4.parent());
      assertFalse(deleteRequest4.getShouldPersistResult());
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest4.consistencyLevel());
      assertEquals("V`T-WkX0bOf", deleteRequest4.routing());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest4.getRefreshPolicy());
      assertEquals(";!yc|<+-F`3&2s!+c|A", deleteRequest4.index());
      assertEquals("", deleteRequest4.id());
      assertEquals("V`T-WkX0bOf", deleteRequest5.routing());
      assertEquals(";!yc|<+-F`3&2s!+c|A", deleteRequest5.index());
      assertEquals("", deleteRequest5.id());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest5.getRefreshPolicy());
      assertNull(deleteRequest5.parent());
      assertEquals(0L, deleteRequest5.primaryTerm());
      assertFalse(deleteRequest5.getShouldPersistResult());
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest5.consistencyLevel());
      assertEquals((-3L), deleteRequest5.version());
      assertEquals(VersionType.EXTERNAL, deleteRequest5.versionType());
      assertNull(deleteRequest5.type());
      
      // Undeclared exception!
      try { 
        TransportDeleteAction.resolveAndValidateRouting(metaData0, string0, deleteRequest4);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.elasticsearch.action.delete.TransportDeleteAction", e);
      }
  }

  @Test(timeout = 11000)
  public void test10()  throws Throwable  {
      String string0 = "";
      String string1 = "";
      DeleteRequest deleteRequest0 = new DeleteRequest(string0, string0, string1);
      assertNotNull(deleteRequest0);
      assertNull(deleteRequest0.routing());
      assertNull(deleteRequest0.parent());
      assertEquals("", deleteRequest0.id());
      assertEquals("", deleteRequest0.index());
      assertEquals(0L, deleteRequest0.primaryTerm());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest0.getRefreshPolicy());
      assertEquals(VersionType.INTERNAL, deleteRequest0.versionType());
      assertEquals((-3L), deleteRequest0.version());
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest0.consistencyLevel());
      assertFalse(deleteRequest0.getShouldPersistResult());
      assertEquals("", deleteRequest0.type());
      
      VersionType versionType0 = VersionType.EXTERNAL_GTE;
      DeleteRequest deleteRequest1 = deleteRequest0.versionType(versionType0);
      assertNotNull(deleteRequest1);
      assertSame(string0, string1);
      assertSame(string1, string0);
      assertSame(deleteRequest0, deleteRequest1);
      assertSame(deleteRequest1, deleteRequest0);
      assertNull(deleteRequest0.routing());
      assertNull(deleteRequest0.parent());
      assertEquals("", deleteRequest0.id());
      assertEquals("", deleteRequest0.index());
      assertEquals(0L, deleteRequest0.primaryTerm());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest0.getRefreshPolicy());
      assertEquals((-3L), deleteRequest0.version());
      assertEquals(VersionType.EXTERNAL_GTE, deleteRequest0.versionType());
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest0.consistencyLevel());
      assertFalse(deleteRequest0.getShouldPersistResult());
      assertEquals("", deleteRequest0.type());
      assertEquals((-3L), deleteRequest1.version());
      assertEquals(VersionType.EXTERNAL_GTE, deleteRequest1.versionType());
      assertEquals(0L, deleteRequest1.primaryTerm());
      assertEquals("", deleteRequest1.type());
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest1.consistencyLevel());
      assertEquals("", deleteRequest1.id());
      assertFalse(deleteRequest1.getShouldPersistResult());
      assertNull(deleteRequest1.routing());
      assertNull(deleteRequest1.parent());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest1.getRefreshPolicy());
      assertEquals("", deleteRequest1.index());
      
      String string2 = "";
      DeleteRequest deleteRequest2 = deleteRequest1.id(string2);
      assertNotNull(deleteRequest2);
      assertSame(string0, string2);
      assertSame(string0, string1);
      assertSame(string1, string2);
      assertSame(string1, string0);
      assertSame(deleteRequest0, deleteRequest2);
      assertSame(deleteRequest0, deleteRequest1);
      assertSame(deleteRequest1, deleteRequest0);
      assertSame(deleteRequest1, deleteRequest2);
      assertSame(string2, string1);
      assertSame(string2, string0);
      assertSame(deleteRequest2, deleteRequest0);
      assertSame(deleteRequest2, deleteRequest1);
      assertNull(deleteRequest0.routing());
      assertNull(deleteRequest0.parent());
      assertEquals("", deleteRequest0.id());
      assertEquals("", deleteRequest0.index());
      assertEquals(0L, deleteRequest0.primaryTerm());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest0.getRefreshPolicy());
      assertEquals((-3L), deleteRequest0.version());
      assertEquals(VersionType.EXTERNAL_GTE, deleteRequest0.versionType());
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest0.consistencyLevel());
      assertFalse(deleteRequest0.getShouldPersistResult());
      assertEquals("", deleteRequest0.type());
      assertEquals((-3L), deleteRequest1.version());
      assertEquals(VersionType.EXTERNAL_GTE, deleteRequest1.versionType());
      assertEquals(0L, deleteRequest1.primaryTerm());
      assertEquals("", deleteRequest1.type());
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest1.consistencyLevel());
      assertEquals("", deleteRequest1.id());
      assertFalse(deleteRequest1.getShouldPersistResult());
      assertNull(deleteRequest1.routing());
      assertNull(deleteRequest1.parent());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest1.getRefreshPolicy());
      assertEquals("", deleteRequest1.index());
      assertEquals((-3L), deleteRequest2.version());
      assertEquals("", deleteRequest2.type());
      assertEquals(VersionType.EXTERNAL_GTE, deleteRequest2.versionType());
      assertEquals("", deleteRequest2.index());
      assertEquals("", deleteRequest2.id());
      assertNull(deleteRequest2.parent());
      assertEquals(0L, deleteRequest2.primaryTerm());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest2.getRefreshPolicy());
      assertFalse(deleteRequest2.getShouldPersistResult());
      assertNull(deleteRequest2.routing());
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest2.consistencyLevel());
      
      String string3 = " st:";
      DeleteRequest deleteRequest3 = deleteRequest2.type(string3);
      assertNotNull(deleteRequest3);
      assertFalse(string0.equals((Object)string3));
      assertFalse(string1.equals((Object)string3));
      assertFalse(string2.equals((Object)string3));
      assertFalse(string3.equals((Object)string0));
      assertFalse(string3.equals((Object)string2));
      assertFalse(string3.equals((Object)string1));
      assertSame(string0, string2);
      assertNotSame(string0, string3);
      assertSame(string0, string1);
      assertSame(string1, string2);
      assertNotSame(string1, string3);
      assertSame(string1, string0);
      assertSame(deleteRequest0, deleteRequest2);
      assertSame(deleteRequest0, deleteRequest3);
      assertSame(deleteRequest0, deleteRequest1);
      assertSame(deleteRequest1, deleteRequest3);
      assertSame(deleteRequest1, deleteRequest0);
      assertSame(deleteRequest1, deleteRequest2);
      assertNotSame(string2, string3);
      assertSame(string2, string1);
      assertSame(string2, string0);
      assertSame(deleteRequest2, deleteRequest3);
      assertSame(deleteRequest2, deleteRequest0);
      assertSame(deleteRequest2, deleteRequest1);
      assertNotSame(string3, string0);
      assertNotSame(string3, string2);
      assertNotSame(string3, string1);
      assertSame(deleteRequest3, deleteRequest2);
      assertSame(deleteRequest3, deleteRequest1);
      assertSame(deleteRequest3, deleteRequest0);
      assertNull(deleteRequest0.routing());
      assertNull(deleteRequest0.parent());
      assertEquals("", deleteRequest0.id());
      assertEquals("", deleteRequest0.index());
      assertEquals(0L, deleteRequest0.primaryTerm());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest0.getRefreshPolicy());
      assertEquals((-3L), deleteRequest0.version());
      assertEquals(" st:", deleteRequest0.type());
      assertEquals(VersionType.EXTERNAL_GTE, deleteRequest0.versionType());
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest0.consistencyLevel());
      assertFalse(deleteRequest0.getShouldPersistResult());
      assertEquals((-3L), deleteRequest1.version());
      assertEquals(" st:", deleteRequest1.type());
      assertEquals(VersionType.EXTERNAL_GTE, deleteRequest1.versionType());
      assertEquals(0L, deleteRequest1.primaryTerm());
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest1.consistencyLevel());
      assertEquals("", deleteRequest1.id());
      assertFalse(deleteRequest1.getShouldPersistResult());
      assertNull(deleteRequest1.routing());
      assertNull(deleteRequest1.parent());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest1.getRefreshPolicy());
      assertEquals("", deleteRequest1.index());
      assertEquals((-3L), deleteRequest2.version());
      assertEquals(" st:", deleteRequest2.type());
      assertEquals(VersionType.EXTERNAL_GTE, deleteRequest2.versionType());
      assertEquals("", deleteRequest2.index());
      assertEquals("", deleteRequest2.id());
      assertNull(deleteRequest2.parent());
      assertEquals(0L, deleteRequest2.primaryTerm());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest2.getRefreshPolicy());
      assertFalse(deleteRequest2.getShouldPersistResult());
      assertNull(deleteRequest2.routing());
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest2.consistencyLevel());
      assertEquals((-3L), deleteRequest3.version());
      assertEquals(VersionType.EXTERNAL_GTE, deleteRequest3.versionType());
      assertEquals(" st:", deleteRequest3.type());
      assertEquals("", deleteRequest3.index());
      assertEquals(0L, deleteRequest3.primaryTerm());
      assertNull(deleteRequest3.parent());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest3.getRefreshPolicy());
      assertEquals("", deleteRequest3.id());
      assertFalse(deleteRequest3.getShouldPersistResult());
      assertNull(deleteRequest3.routing());
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest3.consistencyLevel());
      
      long long0 = (-383L);
      DeleteRequest deleteRequest4 = deleteRequest3.version(long0);
      assertNotNull(deleteRequest4);
      assertFalse(string0.equals((Object)string3));
      assertFalse(string1.equals((Object)string3));
      assertFalse(string2.equals((Object)string3));
      assertFalse(string3.equals((Object)string0));
      assertFalse(string3.equals((Object)string2));
      assertFalse(string3.equals((Object)string1));
      assertSame(string0, string2);
      assertNotSame(string0, string3);
      assertSame(string0, string1);
      assertSame(string1, string2);
      assertNotSame(string1, string3);
      assertSame(string1, string0);
      assertSame(deleteRequest0, deleteRequest2);
      assertSame(deleteRequest0, deleteRequest4);
      assertSame(deleteRequest0, deleteRequest3);
      assertSame(deleteRequest0, deleteRequest1);
      assertSame(deleteRequest1, deleteRequest4);
      assertSame(deleteRequest1, deleteRequest3);
      assertSame(deleteRequest1, deleteRequest0);
      assertSame(deleteRequest1, deleteRequest2);
      assertNotSame(string2, string3);
      assertSame(string2, string1);
      assertSame(string2, string0);
      assertSame(deleteRequest2, deleteRequest4);
      assertSame(deleteRequest2, deleteRequest3);
      assertSame(deleteRequest2, deleteRequest0);
      assertSame(deleteRequest2, deleteRequest1);
      assertNotSame(string3, string0);
      assertNotSame(string3, string2);
      assertNotSame(string3, string1);
      assertSame(deleteRequest3, deleteRequest2);
      assertSame(deleteRequest3, deleteRequest1);
      assertSame(deleteRequest3, deleteRequest0);
      assertSame(deleteRequest3, deleteRequest4);
      assertSame(deleteRequest4, deleteRequest3);
      assertSame(deleteRequest4, deleteRequest0);
      assertSame(deleteRequest4, deleteRequest2);
      assertSame(deleteRequest4, deleteRequest1);
      assertNull(deleteRequest0.routing());
      assertNull(deleteRequest0.parent());
      assertEquals((-383L), deleteRequest0.version());
      assertEquals("", deleteRequest0.id());
      assertEquals("", deleteRequest0.index());
      assertEquals(0L, deleteRequest0.primaryTerm());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest0.getRefreshPolicy());
      assertEquals(" st:", deleteRequest0.type());
      assertEquals(VersionType.EXTERNAL_GTE, deleteRequest0.versionType());
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest0.consistencyLevel());
      assertFalse(deleteRequest0.getShouldPersistResult());
      assertEquals(" st:", deleteRequest1.type());
      assertEquals(VersionType.EXTERNAL_GTE, deleteRequest1.versionType());
      assertEquals(0L, deleteRequest1.primaryTerm());
      assertEquals((-383L), deleteRequest1.version());
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest1.consistencyLevel());
      assertEquals("", deleteRequest1.id());
      assertFalse(deleteRequest1.getShouldPersistResult());
      assertNull(deleteRequest1.routing());
      assertNull(deleteRequest1.parent());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest1.getRefreshPolicy());
      assertEquals("", deleteRequest1.index());
      assertEquals(" st:", deleteRequest2.type());
      assertEquals(VersionType.EXTERNAL_GTE, deleteRequest2.versionType());
      assertEquals((-383L), deleteRequest2.version());
      assertEquals("", deleteRequest2.index());
      assertEquals("", deleteRequest2.id());
      assertNull(deleteRequest2.parent());
      assertEquals(0L, deleteRequest2.primaryTerm());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest2.getRefreshPolicy());
      assertFalse(deleteRequest2.getShouldPersistResult());
      assertNull(deleteRequest2.routing());
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest2.consistencyLevel());
      assertEquals(VersionType.EXTERNAL_GTE, deleteRequest3.versionType());
      assertEquals(" st:", deleteRequest3.type());
      assertEquals("", deleteRequest3.index());
      assertEquals(0L, deleteRequest3.primaryTerm());
      assertNull(deleteRequest3.parent());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest3.getRefreshPolicy());
      assertEquals("", deleteRequest3.id());
      assertFalse(deleteRequest3.getShouldPersistResult());
      assertEquals((-383L), deleteRequest3.version());
      assertNull(deleteRequest3.routing());
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest3.consistencyLevel());
      assertEquals(0L, deleteRequest4.primaryTerm());
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest4.consistencyLevel());
      assertEquals((-383L), deleteRequest4.version());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest4.getRefreshPolicy());
      assertEquals("", deleteRequest4.id());
      assertNull(deleteRequest4.routing());
      assertNull(deleteRequest4.parent());
      assertEquals("", deleteRequest4.index());
      assertFalse(deleteRequest4.getShouldPersistResult());
      assertEquals(" st:", deleteRequest4.type());
      assertEquals(VersionType.EXTERNAL_GTE, deleteRequest4.versionType());
      
      IndexShard indexShard0 = null;
      // Undeclared exception!
      try { 
        TransportDeleteAction.executeDeleteRequestOnPrimary(deleteRequest4, indexShard0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.elasticsearch.action.delete.TransportDeleteAction", e);
      }
  }

  @Test(timeout = 11000)
  public void test11()  throws Throwable  {
      MetaData metaData0 = MetaData.PROTO;
      assertNotNull(metaData0);
      assertEquals(0L, metaData0.version());
      assertEquals(0, metaData0.getNumberOfShards());
      assertEquals(0, metaData0.getTotalNumberOfShards());
      assertEquals("_na_", metaData0.clusterUUID());
      
      String string0 = "";
      String string1 = ".8";
      DeleteRequest deleteRequest0 = new DeleteRequest(string1);
      assertNotNull(deleteRequest0);
      assertFalse(string1.equals((Object)string0));
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest0.consistencyLevel());
      assertNull(deleteRequest0.type());
      assertEquals(0L, deleteRequest0.primaryTerm());
      assertNull(deleteRequest0.parent());
      assertEquals(VersionType.INTERNAL, deleteRequest0.versionType());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest0.getRefreshPolicy());
      assertNull(deleteRequest0.id());
      assertEquals((-3L), deleteRequest0.version());
      assertNull(deleteRequest0.routing());
      assertEquals(".8", deleteRequest0.index());
      assertFalse(deleteRequest0.getShouldPersistResult());
      
      String string2 = "org.elasticsearch.index.query.GeoValidationMethod";
      DeleteRequest deleteRequest1 = deleteRequest0.parent(string2);
      assertNotNull(deleteRequest1);
      assertFalse(string1.equals((Object)string0));
      assertFalse(string1.equals((Object)string2));
      assertFalse(string2.equals((Object)string1));
      assertFalse(string2.equals((Object)string0));
      assertNotSame(string1, string0);
      assertNotSame(string1, string2);
      assertSame(deleteRequest0, deleteRequest1);
      assertNotSame(string2, string1);
      assertNotSame(string2, string0);
      assertSame(deleteRequest1, deleteRequest0);
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest0.consistencyLevel());
      assertNull(deleteRequest0.type());
      assertEquals(0L, deleteRequest0.primaryTerm());
      assertEquals(VersionType.INTERNAL, deleteRequest0.versionType());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest0.getRefreshPolicy());
      assertNull(deleteRequest0.id());
      assertEquals((-3L), deleteRequest0.version());
      assertEquals("org.elasticsearch.index.query.GeoValidationMethod", deleteRequest0.parent());
      assertNull(deleteRequest0.routing());
      assertEquals(".8", deleteRequest0.index());
      assertFalse(deleteRequest0.getShouldPersistResult());
      assertEquals((-3L), deleteRequest1.version());
      assertEquals("org.elasticsearch.index.query.GeoValidationMethod", deleteRequest1.parent());
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest1.consistencyLevel());
      assertNull(deleteRequest1.id());
      assertEquals(0L, deleteRequest1.primaryTerm());
      assertEquals(VersionType.INTERNAL, deleteRequest1.versionType());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest1.getRefreshPolicy());
      assertEquals(".8", deleteRequest1.index());
      assertNull(deleteRequest1.routing());
      assertFalse(deleteRequest1.getShouldPersistResult());
      assertNull(deleteRequest1.type());
      
      TransportDeleteAction.resolveAndValidateRouting(metaData0, string0, deleteRequest1);
      assertFalse(string0.equals((Object)string2));
      assertFalse(string0.equals((Object)string1));
      assertFalse(string1.equals((Object)string0));
      assertFalse(string1.equals((Object)string2));
      assertFalse(string2.equals((Object)string1));
      assertFalse(string2.equals((Object)string0));
      assertNotSame(string0, string2);
      assertNotSame(string0, string1);
      assertNotSame(string1, string0);
      assertNotSame(string1, string2);
      assertSame(deleteRequest0, deleteRequest1);
      assertNotSame(string2, string1);
      assertNotSame(string2, string0);
      assertSame(deleteRequest1, deleteRequest0);
      assertEquals(0L, metaData0.version());
      assertEquals(0, metaData0.getNumberOfShards());
      assertEquals(0, metaData0.getTotalNumberOfShards());
      assertEquals("_na_", metaData0.clusterUUID());
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest0.consistencyLevel());
      assertNull(deleteRequest0.type());
      assertEquals("org.elasticsearch.index.query.GeoValidationMethod", deleteRequest0.routing());
      assertEquals(0L, deleteRequest0.primaryTerm());
      assertEquals(VersionType.INTERNAL, deleteRequest0.versionType());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest0.getRefreshPolicy());
      assertNull(deleteRequest0.id());
      assertEquals((-3L), deleteRequest0.version());
      assertEquals("org.elasticsearch.index.query.GeoValidationMethod", deleteRequest0.parent());
      assertEquals(".8", deleteRequest0.index());
      assertFalse(deleteRequest0.getShouldPersistResult());
      assertEquals((-3L), deleteRequest1.version());
      assertEquals("org.elasticsearch.index.query.GeoValidationMethod", deleteRequest1.routing());
      assertEquals("org.elasticsearch.index.query.GeoValidationMethod", deleteRequest1.parent());
      assertEquals(WriteConsistencyLevel.DEFAULT, deleteRequest1.consistencyLevel());
      assertNull(deleteRequest1.id());
      assertEquals(0L, deleteRequest1.primaryTerm());
      assertEquals(VersionType.INTERNAL, deleteRequest1.versionType());
      assertEquals(WriteRequest.RefreshPolicy.NONE, deleteRequest1.getRefreshPolicy());
      assertEquals(".8", deleteRequest1.index());
      assertFalse(deleteRequest1.getShouldPersistResult());
      assertNull(deleteRequest1.type());
  }
}
